##########################################################
###################  生产环境的profile  ###################
##########################################################
spring:
  datasource:
    url: jdbc:mysql://47.94.145.206:3306/xy?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    db-name: xy
    filters: log4j,wall,mergeStat
  redis:
    host: 47.94.145.206
    port: 6379
    password:

#flowable数据源和多数据源配置
xy:
  flowable:
    datasource:
      url: jdbc:mysql://47.94.145.206:3306/xy_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
  muti-datasource:
    default-dataSource-name: dataSourceXy #默认的数据源名称
    url: jdbc:mysql://47.94.145.206:3306/xy_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root


